### ISSUE TITLE
UL16 PreVFP Data (DoubleEG/..Run2016X..) Not Parsed by fggRunJobs

### ISSUE THREAD

**Issue by neilSchroeder** [cms-analysis/flashgg#1301]
When trying to run on UL16 preVFP DoubleEG datasets with campaign RunIISummer20UL16preVFP, flashgg fggRunJobs.py breaks with the following errors:

Traceback (most recent call last):
  File "/afs/cern.ch/work/n/nschroed/flash_2021-11-30/CMSSW_10_6_29/src/flashgg/Systematics/test/ul16_preVFP_data/workspaceStd.py", line 205, in <module>
    customize.parse()
  File "/afs/cern.ch/work/n/nschroed/flash_2021-11-30/CMSSW_10_6_29/python/flashgg/MetaData/JobConfig.py", line 528, in parse
    dataset = self.samplesMan.getDatasetMetaData(self.options.maxEvents,self.dataset,jobId=-1,nJobs=self.nJobs,weightName=self.WeightName)
  File "/afs/cern.ch/work/n/nschroed/flash_2021-11-30/CMSSW_10_6_29/python/flashgg/MetaData/samples_utils.py", line 862, in getDatasetMetaData
    primary,secondary,tier = primary.split("/")
ValueError: need more than 2 values to unpack

Indicating that flashgg cannot properly read the catalog entries for these datasets.

**Comment by youyingli** [comment]
Sorry for the late response. Just want to understand how to write JSON like [link](https://github.com/cms-analysis/flashgg/blob/3c9a31b0d3fbe35bb659e035dabe5534577c297e/Systematics/test/UL_runII_v1_2017.json#L5L9). I am asking because for real data, you should write the complete name of the MicroAOD.

**Comment by youyingli** [comment]
In order to get the complete name, you can use ```fggManageSamples.py -C RunIISummer20UL16preVFP list raw | grep "DoubleEG"```.
